openapi: "3.0.2"
info:
  title: Charis-Bracelet database-API
  version: "1.0"
servers:
  - url: http://localhost:8080
tags:
  - name: Item
    description: '商品に関するAPI'
  - name: Auth
    description: '管理用API Basic認証が必要です。'
paths:
  /item/top:
    get:
      tags:
        - Item
      description: 'トップページ用の商品一覧を取得します。'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Top_Item_List'
  /item/all:
    get:
      tags:
        - Item
      description: '購入可能な商品を取得します。'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item_List'
  /item/recommend/{Item_ID}:
    post:
      parameters:
      - name: Item_ID
        in: query
        required: true
        schema:
          type: string
          default: 'Item_ID_1'
      tags:
        - Auth
      description: 'おすすめ商品を登録します。'
      responses:
        '200':
          description: OK
    delete:
      parameters:
      - name: Item_ID
        in: query
        required: true
        schema:
          type: string
          default: 'Item_ID_1'
      tags:
        - Auth
      description: 'おすすめ商品を削除します。'
      responses:
        '200':
          description: OK
  /item/{category}:
    parameters:
      - name: category
        in: query
        required: true
        schema:
          type: string
          default: 'カテゴリ'
    get:
      tags:
        - Item
      description: 'カテゴリーごとの商品一覧を取得します。'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
  /item/{Item_ID}:
    parameters:
      - name: Item_ID
        in: query
        required: true
        schema:
          type: string
          default: 'Item_ID_1'
    get:
      tags:
        - Item
      description: 'Item一つのデータを取得します。1枚の商品ページ用。'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item_Details'
  /item/register:
    post:
      tags:
        - Auth
      description: 'Itemを登録します。'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item_Details'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item_Details'

components:
  schemas:
    Item_Details:
      type: object
      properties:
        Item_Id:
          type: string
          default: 'Item_ID_1'
        Item_Name:
          type: string
          default: 'Item_Name_1'
        Stock:
          type: integer
          default: 5
        Price:
          type: integer
          default: 1000
        Description:
          type: string
          default: '説明'
        Category:
          type: string
          default: 'カテゴリ'
        Key_Word:
          type: string
          default: 'キーワード'
        Status:
          type: string
          default: '購入可能かどうか'
    Item:
      type: object
      properties:
        Item_Id:
          type: string
          default: 'Item_ID_1'
        Item_Name:
          type: string
          default: 'Item_Name_1'
        Stock:
          type: integer
          default: 5
        Price:
          type: integer
          default: 1000
        Status:
          type: string
          default: '購入可能かどうか'
    Item_List:
      type: array
      items:
        $ref: '#/components/schemas/Item'
    Top_Item:
      type: object
      properties:
        Item_Name:
          type: string
          default: 'Item_Name_1'
        Stock:
          type: integer
          default: 5
    Top_Item_List:
      type: array
      items:
        $ref: '#/components/schemas/Top_Item'

        